version: 2

models:

  - name: raw_location
    description: ""
    columns:
      - name: city_name
        description: ""
      - name: base
        description: "type of station"
      - name: timezone
        description: ""
      - name: lat
        description: ""
      - name: lon
        description: ""
      - name: country
        description: ""

  - name: raw_weather
    description: ""
    columns:
      - name: dt
        description: "unix time"
      - name: city_name
        description: ""
      - name: cloud_cover
        description: "cloud cover percentage"
      - name: wind_deg
        description: "Wind direction, degrees (meteorological)"
      - name: wind_speed
        description: "Wind speed. Unit Default: meter/sec"
      - name: pressure
        description: "Pressure units, hPa"
      - name: temp_k
        description: "Temperature. Unit Default: Kelvin"
      - name: humidity
        description: "Humidity, %"
      - name: visibility
        description: "Visibility, meter. The maximum value of the visibility is 10 km"